application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout, login
from playlist.views import PlaylistList
from core.views import RegisterFormView

urlpatterns = [
    url(r'^$', PlaylistList.as_view(), name="playlist_list"),
    url(r'^admin/', admin.site.urls),
    url(r'^audiotrack/', include('audiotrack.urls', namespace="audiotrack")),
    url(r'^playlists/', include('playlist.urls', namespace="playlist")),
    url(r'^login/$', login, {'template_name': 'registration/login.html'}, name="login"),
    url(r'^logout/$', logout, {'template_name': 'registration/logged.html'}, name="logout"),
    url(r'^register/$', RegisterFormView.as_view()),
    # url('^', include('django.contrib.auth.urls'))
]

audiotrack/urls.py
from django.conf.urls import url
from .views import AudiotrackList, AudiotrackView, AudiotrackCreateView, AudiotrackModifyView

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', AudiotrackView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/modify$', AudiotrackModifyView.as_view(), name="modify"),
    url(r'^create/$', AudiotrackCreateView.as_view(), name='audiotrack_create'),
    url(r'^$', AudiotrackList.as_view(), name="audiotrack_list"),
    url(r'^add/$', 'audiotrack.views.add', name='add'),
]

playlist/urls.py
from django.conf.urls import url
from .views import PlaylistList, PlaylistView, PlaylistCreateView, PlaylistUpdate

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', PlaylistView.as_view(), name="playlist_detail"),
    url(r'^(?P<pk>\d+)/update', PlaylistUpdate.as_view(), name="update"),
    url(r'^$', PlaylistList.as_view(), name="playlist_list"),
    url(r'^create/$', PlaylistCreateView.as_view(), name="playlist_create"),
    url(r'^like/$', 'playlist.views.like', name='like'),
]

audiotrack/models.py
# coding: utf-8

from __future__ import unicode_literals

from django.db import models
from django.conf import settings

class Audiotrack(models.Model):

    name = models.CharField(verbose_name=u'Название трека', max_length=255)

    url = models.CharField(blank=True, verbose_name=u'Адрес трека', max_length=255)
    audio_file = models.FileField(null=True, blank=True, upload_to='uploads/')

    tags = models.ManyToManyField("tags.Tag", verbose_name=u'Теги')

    length = models.FloatField(blank=True)

    created_at = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)
    changed_at = models.DateTimeField(verbose_name=u'Дата последнего изменения', auto_now_add=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Аудиотрек'
        verbose_name_plural = u'Аудиотреки'
        ordering = ('-name', )

audiotrack/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Audiotrack


class AudiotrackListForm(forms.Form):

    search = forms.CharField(required=False)
    sort_field = forms.ChoiceField(choices=(('name', 'Name'), ('id', 'ID'), ('created_at', u'Дата создания')), required=False)

    def clean_search(self):
        search = self.cleaned_data.get('search')
        # raise forms.ValidationError(u'Я неправильный поиск!')
        return search


class AudiotrackCreateForm(forms.Form):

    title = forms.CharField(max_length=255)
    url = forms.CharField(widget=forms.Textarea, required=False)
    audio_file = forms.FileField(required=False)


#widget_tweaks
class AudiotrackModifyForm(forms.ModelForm):
    class Meta:
        model = Audiotrack
        fields = ('name', 'url', 'tags')

audiotrack/views.py
from django.contrib.auth.decorators import login_required
try:
    from django.utils import simplejson as json
except ImportError:
    import json
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, resolve_url
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, CreateView, UpdateView
from django.views.generic import ListView
from playlist.models import Playlist
from .forms import AudiotrackListForm, AudiotrackCreateForm, AudiotrackModifyForm
from .models import Audiotrack


class AudiotrackCreateView(CreateView):
    model = Audiotrack
    fields = ('name', 'url', 'audio_file')
    template_name = 'audiotrack/create.html'

    def dispatch(self, request, *args, **kwargs):
        self.form = AudiotrackCreateForm(request.POST or None)
        self.form.is_valid()
        return super(AudiotrackCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.length = 0

        # img = self.get_form_kwargs().get('files')['audio_file']
        # form.instance.audio_file = img;

        obj = Audiotrack(
            name = form.instance.name,
            url = form.instance.url,
            audio_file = self.get_form_kwargs().get('files').get('audio_file'),
            length = 0,
            author = self.request.user)
        obj.save()
        self.id = obj.id
        return HttpResponseRedirect(self.get_success_url())
        # return super(AudiotrackCreateView, self).form_valid(form)

    def get_success_url(self):
        return resolve_url('audiotrack:detail', pk=self.id)


class AudiotrackView(DetailView):
    model = Audiotrack
    template_name = 'audiotrack/audiotrack.html'
    context_object_name = 'audiotrack'

    def get_context_data(self, **kwargs):
        context = super(AudiotrackView, self).get_context_data(**kwargs)

        context['playlists'] = Playlist.objects.all()
        return context


class AudiotrackModifyView(UpdateView):
    model = Audiotrack
    template_name = 'audiotrack/modify.html'
    context_object_name = 'audiotrack'

    # fields = ('name', 'url', 'tags')
    form_class = AudiotrackModifyForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(AudiotrackModifyView, self).form_valid(form)

    # def get_context_data(self, **kwargs):
    #     context = super(AudiotrackModifyView, self).get_context_data(**kwargs)
    #     context['modify_form'] = self.modify_form
    #     return context

    def get_success_url(self):
        return resolve_url('audiotrack:detail', pk=self.object.pk)


class AudiotrackList(ListView):
    model = Audiotrack
    template_name = 'audiotrack/audiotracks.html'

    def dispatch(self, request, *args, **kwargs):
        self.form = AudiotrackListForm(request.GET)
        self.form.is_valid()
        self.create_form = AudiotrackCreateForm(request.POST or None)
        return super(AudiotrackList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        #exception when logout
        queryset = Audiotrack.objects.filter(author=self.request.user)
        if self.form.cleaned_data.get('search'):
            # queryset = queryset.filter(name=self.form.cleaned_data['search'])
            queryset = queryset.filter(name__contains=self.form.cleaned_data['search'])
        if self.form.cleaned_data.get('sort_field'):
            queryset = queryset.order_by(self.form.cleaned_data['sort_field'])[:10]
        return queryset

    def get_context_data(self, **kwargs):
        context = super(AudiotrackList, self).get_context_data(**kwargs)
        context['form'] = self.form
        context['create_form'] = self.create_form
        return context

@login_required
@require_POST
def add(request):
    if request.method == 'POST':
        user = request.user
        track_id = request.POST.get('track_id', None)
        playlist_id = request.POST.get('playlist_id', None)
        print "track_id", track_id
        print "playlist_id", playlist_id
        Playlist.objects.get(id=playlist_id).audiotracks.add(Audiotrack.objects.get(id=track_id))
    ctx = {'message':'completed'}
    return HttpResponse(json.dumps(ctx), content_type='application/json')

audiotrack/templates/audiotrack/audiotrack.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link type="text/css" rel="stylesheet" href="{% static 'audiotrack/css/tracklist.css' %}"/>
{% endblock %}

{% block title %}
<div> {{ audiotrack.name }}</div>
{% endblock %}

{% block content %}

<script src="{% static 'audiotrack/js/audiotrack.js' %}"></script>


<div> {{ audiotrack.url }}</div>

{% if audiotrack.author == user %}
<div>
    <a href="{% url 'audiotrack:modify' pk=audiotrack.id %}">Modify</a>
</div>
{% endif %}

{% for tagg in audiotrack.tags.all %}
<div class="chip">
    {{ tagg.name }}
</div>
{% endfor %}

<div>
    <label>Add to Playlist</label>
    <select id="choose_playlist" class="browser-default select--item">
        <option value="" disabled selected>Choose playlist</option>

        {% for plist in playlists %}
        <option value="{{ plist.id }}">{{ plist.name }}</option>

        {% endfor %}

    </select>
    <a id="add_track_to_playlist" class="waves-effect waves-light btn select--item"
       data-token="{{ csrf_token }}" data-url="{% url 'audiotrack:add' %}">Add</a>
</div>

<div id="result" class="chip">
</div>
<div id="audiotrack_data" data-audiotrack-id="{{ audiotrack.id }}"></div>


<div class="input-field col s12">
    <select multiple>
      <option value="" disabled selected>Choose your option</option>
      <option value="1">Option 1</option>
      <option value="2">Option 2</option>
      <option value="3">Option 3</option>
    </select>
    <label>Materialize Multiple Select</label>
  </div>

{% endblock %}

audiotrack/templates/audiotrack/audiotracks.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link type="text/css" rel="stylesheet" href="{% static 'audiotrack/css/tracklist.css' %}"/>
{% endblock %}

{% block title %}
Audiotracks
{% endblock %}

{% block content %}

<form>
    {{ form.search }} {{ form.sort_field }} {{ form.errors }}
    <input type="submit" value="submit">
</form>

<div>
    <a href="{% url 'audiotrack:audiotrack_create' %}"/>
</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 30%;">
    <a class="btn-floating btn-large red" href="{% url 'audiotrack:audiotrack_create' %}">
        <i class="large material-icons">mode_edit</i>
    </a>
</div>

<div>
    <ul class="collection">

        {% for at in object_list %}

        <li class="collection-item avatar tracklist--item">
            <i class="material-icons circle red">play_arrow</i>
            <a href="{% url 'audiotrack:detail' pk=at.id %}">

                <span class="title">{{ at.name }}</span>

                <p>{{ at.url }}</p>
                <!--<a href="{% url 'audiotrack:detail' pk=at.id %}" class="secondary-content"><i-->
                <!--class="material-icons">grade</i></a>-->
            </a>
        </li>

        {% endfor %}
    </ul>
</div>

{% endblock %}

audiotrack/templates/audiotrack/create.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form }}

    {{ form.tags|add_class:"input-field col s12" }}

    <input type="submit"> save </input>
</form>
{% endblock %}

audiotrack/templates/audiotrack/modify.html
{% extends "base.html" %}

{% block title %}
<div> Name: {{ audiotrack.name }}</div>
<div> Url: {{ audiotrack.url }}</div>
{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">Save</input>
</form>


{% endblock %}