application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout, login
from playlist.views import PlaylistList
from core.views import RegisterFormView

urlpatterns = [
    url(r'^$', PlaylistList.as_view(), name="playlist_list"),
    url(r'^admin/', admin.site.urls),
    url(r'^audiotrack/', include('audiotrack.urls', namespace="audiotrack")),
    url(r'^playlists/', include('playlist.urls', namespace="playlist")),
    url(r'^login/$', login, {'template_name': 'registration/login.html'}, name="login"),
    url(r'^logout/$', logout, {'template_name': 'registration/logged.html'}, name="logout"),
    url(r'^register/$', RegisterFormView.as_view()),
    # url('^', include('django.contrib.auth.urls'))
]

audiotrack/urls.py
from django.conf.urls import url
from .views import AudiotrackList, AudiotrackView, AudiotrackCreateView, AudiotrackModifyView

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', AudiotrackView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/modify$', AudiotrackModifyView.as_view(), name="modify"),
    url(r'^create/$', AudiotrackCreateView.as_view(), name='audiotrack_create'),
    url(r'^$', AudiotrackList.as_view(), name="audiotrack_list"),
    url(r'^add/$', 'audiotrack.views.add', name='add'),
]

playlist/urls.py
from django.conf.urls import url
from .views import PlaylistList, PlaylistView, PlaylistCreateView, PlaylistUpdate

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', PlaylistView.as_view(), name="playlist_detail"),
    url(r'^(?P<pk>\d+)/update', PlaylistUpdate.as_view(), name="update"),
    url(r'^$', PlaylistList.as_view(), name="playlist_list"),
    url(r'^create/$', PlaylistCreateView.as_view(), name="playlist_create"),
    url(r'^like/$', 'playlist.views.like', name='like'),
]

playlist/models.py
# coding: utf-8

from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Playlist(models.Model):

    name = models.CharField(verbose_name=u'Название плейлиста', max_length=255)

    audiotracks = models.ManyToManyField('audiotrack.Audiotrack', verbose_name=u'Список треков', related_name="playlists")

    created_at = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)
    changed_at = models.DateTimeField(verbose_name=u'Дата последнего изменения', auto_now_add=True)

    is_private = models.BooleanField(default=True, verbose_name=u'Закрытый плейлист')

    likes = models.ManyToManyField(User, related_name='likes')

    slug = models.SlugField(default=0)

    @property
    def total_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Playlist, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Плейлист'
        verbose_name_plural = u'Плейлисты'
        ordering = ('-name', )

playlist/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Playlist


class PlaylistCreateForm(forms.Form):

    #name = forms.CharField(max_length=255)
    is_private = forms.BooleanField(required=False)

playlist/views.py
from django.db.models import Sum
from django.http import HttpResponse

try:
    from django.utils import simplejson as json
except ImportError:
    import json
from django.shortcuts import resolve_url
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .forms import PlaylistCreateForm
from .models import Playlist
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404


class PlaylistView(DetailView):
    model = Playlist
    template_name = 'playlist/playlist.html'
    context_object_name = 'playlist'

    def get_context_data(self, **kwargs):
        context = super(PlaylistView, self).get_context_data(**kwargs)
        context["sum_length"] = self.object.audiotracks.all().aggregate(a=Sum('length'))['a']
        return context


class PlaylistList(ListView):
    model = Playlist
    template_name = 'playlist/playlists.html'


class PlaylistCreateView(CreateView):
    model = Playlist
    fields = ('name', 'is_private')
    template_name = 'playlist/playlist_create.html'

    def dispatch(self, request, *args, **kwargs):
        self.form = PlaylistCreateForm(request.POST or None)
        self.form.is_valid()
        return super(PlaylistCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PlaylistCreateView, self).form_valid(form)

    def get_success_url(self):
        return resolve_url('playlist:playlist_detail', pk=self.object.pk)


class PlaylistUpdate(UpdateView):
    model = Playlist

    context_object_name = 'playlist'
    template_name = 'playlist/update.html'

    fields = ('name', 'is_private')

    def get_success_url(self):
        return resolve_url('playlist:playlist_detail', pk=self.object.pk)


@login_required
@require_POST
def like(request):
    if request.method == 'POST':
        user = request.user
        # todo del slug, get by tag
        slug = request.POST.get('slug', None)
        playlist = get_object_or_404(Playlist, slug=slug)

        if playlist.likes.filter(id=user.id).exists():
            playlist.likes.remove(user)
            message = 'You disliked this'
        else:
            playlist.likes.add(user)
            message = 'You liked this'

    ctx = {'likes_count': playlist.total_likes, 'message': message}
    # use mimetype instead of content_type if django < 5
    return HttpResponse(json.dumps(ctx), content_type='application/json')

playlist/templates/playlist/player.html
<div class='jAudio--player' id='player'>

    <audio></audio>

    <div class='jAudio--ui'>

        <div class='jAudio--thumb'></div>

        <div class='jAudio--status-bar'>

            <div class='jAudio--details'></div>
            <div class='jAudio--volume-bar'></div>

            <div class='jAudio--progress-bar'>
                <div class='jAudio--progress-bar-wrapper'>
                    <div class='jAudio--progress-bar-played'>
                        <span class='jAudio--progress-bar-pointer'></span>
                    </div>
                </div>
            </div>

            <div class='jAudio--time'>
                <span class='jAudio--time-elapsed'>00:00</span>
                <span class='jAudio--time-total'>00:00</span>
            </div>

        </div>

    </div>


    <div class='jAudio--playlist'>
    </div>

    <div class='jAudio--controls'>
        <ul>
            <li>
                <button class='btn' data-action='prev' id='btn-prev'><span></span></button>
            </li>
            <li>
                <button class='btn' data-action='play' id='btn-play'><span></span></button>
            </li>
            <li>
                <button class='btn' data-action='next' id='btn-next'><span></span></button>
            </li>
        </ul>
    </div>

</div>

playlist/templates/playlist/playlist.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
Title:
{{ playlist.name }}
{% endblock %}

{% block content %}

<div id="showl" class="chip" >
    {{ playlist.likes.count }}

</div>

<a class="btn-floating btn-large waves-effect waves-light red" id="like" name="{{ playlist.slug }}" value="Like" data-id="#like"
           data-url="{% url 'playlist:like' %}" data-token="{{ csrf_token }}">
    <i class="material-icons">star</i>
</a>

<script src="{% static 'playlist/js/like.js' %}"></script>

{% if playlist.is_private %}
<div>Private playlist</div>
{% else %}
<div>Public playlist</div>
{% endif %}

<div>
    <button id="play_it" class="btn waves-effect waves-light" type="submit" name="action">Play
        <i class="material-icons right">send</i>
    </button>
</div>

<div>
    Summury length of songs: {{ sum_length }}
</div>

<table>
    <thead>
    <tr>
        <th data-field="id">Name</th>
        <th data-field="name">Url</th>
        <th data-field="price">Item Price</th>
    </tr>
    </thead>

    <tbody>
    {% for audiotrack in playlist.audiotracks.all %}
    <tr>
        <td>{{ audiotrack.name }}</td>
        <td><a href="{% url 'audiotrack:detail' pk=audiotrack.id %}">Url</a></td>
        <td>tmp</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<div id="player_data"
     data-songs-urls="{% for audiotrack in playlist.audiotracks.all %}
     {{audiotrack.audio_file.url}},
     {% endfor %}"></div>
<script src="{% static 'core/js/jaudio.js' %}"></script>


{% endblock %}

playlist/templates/playlist/playlist_create.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit"> Save </input>
</form>
{% endblock %}

playlist/templates/playlist/playlists.html
{% extends "base.html" %}

{% block title %}
Playlists
{% endblock %}

{% block content %}

<div class="row">
    {% for playlist in object_list %}
    <div class="col s3 m3">
        <div class="card">
            <div class="card-image">
                <img src="http://materializecss.com/images/sample-1.jpg">
                <span class="card-title">{{ playlist.name }}</span>
            </div>
            <div class="card-action">
                <a href="{% url 'playlist:playlist_detail' pk=playlist.id %}">Playlist Details</a>
            </div>
            <div class="card-action">
                <a href="#">This is a link</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div><a href="{% url 'playlist:playlist_create' %}">Create playlist</a></div>

{% endblock %}

playlist/templates/playlist/update.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
<div> Name: {{ audiotrack.name }}</div>
{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    <div>
        {{ form.name }}
    </div>
    <div>
        {{ form.is_private }}
    </div>
    <input type="submit" value="Save"/>
</form>


{% endblock %}