application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout, login
from playlist.views import PlaylistList
from core.views import RegisterFormView

urlpatterns = [
    url(r'^$', PlaylistList.as_view(), name="playlist_list"),
    url(r'^admin/', admin.site.urls),
    url(r'^audiotrack/', include('audiotrack.urls', namespace="audiotrack")),
    url(r'^playlists/', include('playlist.urls', namespace="playlist")),
    url(r'^login/$', login, {'template_name': 'registration/login.html'}, name="login"),
    url(r'^logout/$', logout, {'template_name': 'registration/logged.html'}, name="logout"),
    url(r'^register/$', RegisterFormView.as_view()),
    # url('^', include('django.contrib.auth.urls'))
]

audiotrack/urls.py
from django.conf.urls import url
from .views import AudiotrackList, AudiotrackView, AudiotrackCreateView, AudiotrackModifyView

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', AudiotrackView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/modify$', AudiotrackModifyView.as_view(), name="modify"),
    url(r'^create/$', AudiotrackCreateView.as_view(), name='audiotrack_create'),
    url(r'^$', AudiotrackList.as_view(), name="audiotrack_list"),
    url(r'^add/$', 'audiotrack.views.add', name='add'),
]

playlist/urls.py
from django.conf.urls import url
from .views import PlaylistList, PlaylistView, PlaylistCreateView, PlaylistUpdate

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', PlaylistView.as_view(), name="playlist_detail"),
    url(r'^(?P<pk>\d+)/update', PlaylistUpdate.as_view(), name="update"),
    url(r'^$', PlaylistList.as_view(), name="playlist_list"),
    url(r'^create/$', PlaylistCreateView.as_view(), name="playlist_create"),
    url(r'^like/$', 'playlist.views.like', name='like'),
]

core/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/views.py
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm

class RegisterFormView(FormView):
    form_class = UserCreationForm

    success_url = "/login/"

    template_name = "registration/register.html"

    def form_valid(self, form):
        form.save()

        return super(RegisterFormView, self).form_valid(form)

core/templates/base.html
<!DOCTYPE html>


<html lang="en">
<head>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <title>Title</title>

    <link type="text/css" rel="stylesheet" href="{% static 'core/css/audioplayer.css' %}"/>

    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'core/css/materialize.css' %}"
          media="screen,projection"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    {% block head %} {% endblock %}
</head>
<body>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="{% static 'core/js/materialize.min.js' %}"></script>

<div>
    <ul id="slide-out" class="side-nav">
        <li><a href="{% url 'playlist:playlist_list' %}">Playlists</a></li>
        <li><a href="{% url 'audiotrack:audiotrack_list' %}">Audiotracks</a></li>
        <li><a href="{% url 'audiotrack:audiotrack_create' %}">Create audiotrack</a></li>
        <li>
            {% if user.is_anonymous %}
            <a href="{% url 'login' %}">Login</a>
            {% else %}
            <a href="{% url 'logout' %}">Logout</a>
            {% endif %}
        </li>
    </ul>
</div>


<div class="row navbar-fixed">
    <nav class="col s9">
        <ul>
            <li>
                <a href="#" data-activates="slide-out" class="left button-collapse show-on-large"><i
                        class="mdi-navigation-menu"></i></a>
            </li>
            <li><a href="#">{% block title %} {% endblock %}</a></li>
            <li class="right">
                {{ user }}
            </li>
        </ul>
    </nav>

    <nav class="col s3 offset-s9">
        <ul>
            <li><a href="{% url 'playlist:playlist_list' %}">AnyButton</a></li>
        </ul>
    </nav>
</div>

<div class="row">
    <div class="col s9">
        {% block content %} {% endblock %}
    </div>
    <div class="col s3">
        <!--AUDIO PLAYER-->
        <!--<audio src="sound.mp3" controls></audio>-->

        {% include 'playlist/player.html' %}
    </div>
</div>


<!--<script> $(".button-collapse").sideNav(); </script>-->


<script src="{% static 'core/js/jaudio.js' %}"></script>

<script src="{% static 'core/js/side-nav.js' %}"></script>




<!--<script src='resources/js/jaudio.min.js'></script>-->


</body>
</html>